ARC/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^timeinout$', views.timeinout, name='timeinout'),
    url(r'^register$', views.register, name='register'),
    url(r'^pending$', views.pending, name='pending'),

    #<--------------DIRECTORIES------------>

    #<--ADMIN-->
    #Dashboard
    url(r'^Admin$', views.AdminDashboard, name='Admin/Dashboard'),
    url(r'^Admin/Calendar$', views.AdminCalendar, name='Admin/Calendar'),
    #Accounts
    url(r'^Admin/ManageUsers$', views.AdminManageUsers, name='Admin/ManageUsers'),
    url(r'Admin/AddUser$', views.AdminAddUser, name='Admin/AddUser'),
    #Inventory
    url(r'^Admin/ViewInventory$', views.AdminViewInventory, name='Admin/ViewInventory'),
    url(r'^Admin/AddItem$', views.AdminAddItem, name='Admin/AddItem'),
    #Residency
    url(r'^Admin/ViewResidencies$', views.AdminViewResidencies, name='Admin/ViewResidencies'),
    url(r'^Admin/EvaluateResidency$', views.AdminEvaluateResidency, name='Admin/EvaluateResidency'),
    url(r'^Admin/ManageTerm$', views.AdminManageTerm, name='Admin/ManageTerm'),
    #Item Lending
    url(r'^Admin/BorrowItem$', views.AdminBorrowItem, name='Admin/BorrowItem'),
    url(r'^Admin/ReturnItem$', views.AdminReturnItem, name='Admin/ReturnItem'),
    url(r'^Admin/ReturnItem2$', views.AdminReturnItem2, name='Admin/ReturnItem2'),
    #Reports
    url(r'^Admin/ResidencyReport$', views.AdminResidencyReport, name='Admin/ResidencyReport'),
    url(r'^Admin/InventoryReport$', views.AdminInventoryReport, name='Admin/InventoryReport'),
    #Inbox
    url(r'^Admin/Inbox$', views.AdminInbox, name='Admin/Inbox'),
    #Laboratory
    url(r'^Admin/AddLaboratory', views.AdminAddLaboratory, name='Admin/AddLaboratory'),
    url(r'^Admin/EditLaboratory$', views.AdminEditLaboratory, name='Admin/EditLaboratory'),

    #<--END-->

    #<--STUDENT-->
    #Profile
    url(r'Student/Profile$', views.StudentProfile, name='Student/Profile'),
    #Dashboard
    url(r'^Student$', views.StudentDashboard, name='Student/Dashboard'),
    url(r'^Student/Home$', views.StudentHome, name='Student/Home'),
    #Item Lending
    url(r'^Student/BorrowItem$', views.StudentBorrowItem, name='Student/BorrowItem'),
    url(r'^Student/ReturnItem$', views.StudentReturnItem, name='Student/ReturnItem'),
    url(r'^Student/ReturnItem2$', views.StudentReturnItem2, name='Student/ReturnItem2'),
    #Inbox
    url(r'^Student/Inbox$', views.StudentInbox, name='Student/Inbox'),
    #Residency
    url(r'Student/SetResidency$', views.StudentSetResidency, name='Student/SetResidency'),
    url(r'Student/EditResidency$', views.StudentEditResidency, name='Student/EditResidency'),
    #Reports
    url(r'Student/GroupInventory$', views.StudentGroupInventory, name='Student/GroupInventory'),
    url(r'^Student/ResidencyReport$', views.StudentResidencyReport, name='Student/ResidencyReport'),
    #<--END-->

    #<--FACULTY-->
    #Dashboard
    url(r'^Faculty$', views.FacultyDashboard, name='Faculty/Dashboard'),
    url(r'^Faculty/Calendar$', views.FacultyCalendar, name='Faculty/Calendar'),
	url(r'^Faculty/Profile$', views.FacultyProfile, name='Faculty/Profile'),
    #Groups
    url(r'Admin/EvaluateUser$', views.AdminEvaluateUser, name='Admin/EvaluateUser'),
    url(r'Faculty/ManageGroups$', views.FacultyManageGroups, name='Faculty/ManageGroups'),
    url(r'Faculty/AddGroup$', views.FacultyAddGroup, name='Faculty/AddGroup'),
    url(r'Faculty/EditGroup$', views.FacultyEditGroup, name='Faculty/EditGroup'),
    #Residency
    url(r'^Faculty/ViewResidencies$', views.FacultyViewResidencies, name='Faculty/ViewResidencies'),
    #Item Lending
    url(r'^Faculty/BorrowItem$', views.FacultyBorrowItem, name='Faculty/BorrowItem'),
    url(r'^Faculty/ReturnItem$', views.FacultyReturnItem, name='Faculty/ReturnItem'),
    url(r'^Faculty/ReturnItem2$', views.FacultyReturnItem2, name='Faculty/ReturnItem2'),
    #Reports
    url(r'^Faculty/InventoryReport$', views.FacultyInventoryReport, name='Faculty/InventoryReport'),
    url(r'^Faculty/ResidencyReport$', views.FacultyResidencyReport, name='Faculty/ResidencyReport'),
    #Inbox
    url(r'^Faculty/Inbox$', views.FacultyInbox, name='Faculty/Inbox'),
    #<--END-->

    #<--TECHNICIAN AND FACULTY-TECHNICIAN-->
    #Dashboard
    url(r'^FacultyTech$', views.FacultyTechDashboard, name='FacultyTech/Dashboard'),
    url(r'^FacultyTech/Calendar$', views.FacultyTechCalendar, name='FacultyTech/Calendar'),
	url(r'^FacultyTech/Profile$', views.FacultyTechProfile, name='FacultyTech/Profile'),
	url(r'^FacultyTech/ManageStudents$', views.FacultyTechManageStudents, name='FacultyTech/ManageStudents'),
    #Inventory
    url(r'^FacultyTech/AddItem$', views.FacultyTechAddItem, name='FacultyTech/AddItem'),
    url(r'^FacultyTech/ManageItems$', views.FacultyTechManageItems, name='FacultyTech/ManageItems'),
    #Residency
    url(r'^FacultyTech/AddGroup$', views.FacultyTechAddGroup, name='FacultyTech/AddGroup'),
    url(r'^FacultyTech/ManageGroups$', views.FacultyTechManageGroups, name='FacultyTech/ManageGroups'),
    #Residency
    url(r'^FacultyTech/ViewResidencies$', views.FacultyTechViewResidencies, name='FacultyTech/ViewResidencies'),
    url(r'^FacultyTech/EvaluateResidency$', views.FacultyTechEvaluateResidency, name='FacultyTech/EvaluateResidency'),
    url(r'^FacultyTech/ManageTerm$', views.FacultyTechManageTerm, name='FacultyTech/ManageTerm'),
    #Item Lending
    url(r'^FacultyTech/BorrowItem$', views.FacultyTechBorrowItem, name='FacultyTech/BorrowItem'),
    url(r'^FacultyTech/ReturnItem$', views.FacultyTechReturnItem, name='FacultyTech/ReturnItem'),
    url(r'^FacultyTech/ReturnItem2$', views.FacultyTechReturnItem2, name='FacultyTech/ReturnItem2'),
    #Reports
    url(r'^FacultyTech/ResidencyReport$', views.FacultyTechResidencyReport, name='FacultyTech/ResidencyReport'),
    url(r'^FacultyTech/InventoryReport$', views.FacultyTechInventoryReport, name='FacultyTech/InventoryReport'),
    url(r'^FacultyTech/BorrowedItems$', views.FacultyTechBorrowedItems, name='FacultyTech/BorrowedItems'),
    url(r'^FacultyTech/LabReport$', views.FacultyTechLabReport, name='FacultyTech/LabReport'),
    url(r'^FacultyTech/TimeslotReport$', views.FacultyTechTimeslotReport, name='FacultyTech/TimeslotReport'),
    url(r'^FacultyTech/GroupsInventory$', views.FacultyTechGroupsInventory, name='FacultyTech/GroupsInventory'),
    #Inbox
    url(r'^FacultyTech/Inbox$', views.FacultyTechInbox, name='FacultyTech/Inbox'),
    #<--END-->



	#AJAX
    url(r'ajax/editlab', views.EditLabAjax, name='Admin/EditLabAjax'),
    url(r'ajax/borrowitem', views.BorrowItemAjax, name='FacultyTech/BorrowItemAjax'),
    url(r'ajax/manualborrowitem', views.BorrowItemManAjax, name='FacultyTech/BorrowItemManAjax'),
    url(r'ajax/getuserinfo', views.UserInfoAjax, name='FacultyTech/UserInfoAjax'),
    url(r'ajax/manageusers', views.EditUserAjax, name='Admin/EditUserAjax'),
    url(r'ajax/managegroups', views.EditGroupAjax, name='Admin/EditGroupAjax'),
    url(r'ajax/schedajax', views.SchedAjax, name='Admin/SchedAjax'),
    url(r'ajax/setresidency', views.SetResidencyAjax, name='Admin/SetResidencyAjax'),
    url(r'ajax/evaluser', views.EvalUserAjax, name='Admin/EvalUserAjax'),
    url(r'ajax/manageitems', views.ManageItemsAjax, name='FacultyTech/ManageItemsAjax'),
    url(r'ajax/itemdetails', views.ItemDetailsAjax, name='FacultyTech/ItemDetailsAjax'),
    url(r'ajax/itemlog', views.ItemLogAjax, name='FacultyTech/ItemLogAjax'),
    url(r'ajax/edititem', views.EditItemAjax, name='FacultyTech/EditItemAjax'),
	
	
	#NEW AJAX KIM
    url(r'ajax/getBorrowed', views.getBorrowed, name='getBorrowed'),
	url(r'ajax/returnItem', views.returnItem, name='returnItem'),
	url(r'ajax/getUserTimeInInfo', views.getUserTimeInInfo, name='getUserTimeInInfo'),
	#NFC
	url(r'ajax/nfcajax', views.NFCAjax, name='NFCAjax'),
	url(r'ajax/rfidajax', views.RFIDAjax, name='RFIDAjax'),
    #<-----------END OF DIRECTORIES--------->

#<--TECHNICIAN-->
    #Dashboard
    url(r'^Technician$', views.TechnicianDashboard, name='Technician/Dashboard'),
    url(r'^Technician/Calendar$', views.TechnicianCalendar, name='Technician/Calendar'),
    url(r'^Technician/Profile$', views.TechnicianProfile, name='Technician/Profile'),
    #Inventory
    url(r'^Technician/AddItem$', views.TechnicianAddItem, name='Technician/AddItem'),
    #Item Lending
    url(r'^Technician/BorrowItem$', views.TechnicianBorrowItem, name='Technician/BorrowItem'),
    url(r'^Technician/ReturnItem$', views.TechnicianReturnItem, name='Technician/ReturnItem'),
    url(r'^Technician/ReturnItem2$', views.TechnicianReturnItem2, name='Technician/ReturnItem2'),
    #Reports
    url(r'^Technician/BorrowedItems$', views.TechnicianBorrowedItems, name='Technician/BorrowedItems'),
    url(r'^Technician/GroupsInventory$', views.TechnicianGroupsInventory, name='Technician/GroupsInventory'),
    #Inbox
    url(r'^Technician/Inbox$', views.TechnicianInbox, name='Technician/Inbox'),
    #<--END-->
    ]

ThesisProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^auth/', include('social_django.urls', namespace='social')),  # For Google Authentication

    path('admin/', admin.site.urls),
    path('', include('ARC.urls')), #default Log-in page
]

ARC/models.py
from django.db import models
import datetime

# Create your models here.
class Ref_UserType(models.Model):
	UserTypeID = models.AutoField(primary_key=True)
	UserType = models.CharField(max_length=50, default='')

	def natural_key(self):
		return self.UserType, self.UserTypeID

class Ref_UserStatus(models.Model):
	UserStatusID = models.AutoField(primary_key=True)
	UserStatus = models.CharField(max_length=50)

class Ref_Degree(models.Model):
	DegreeID = models.AutoField(primary_key=True)
	DegreeName = models.CharField(max_length=50)

	def natural_key(self):
		return self.DegreeName

class Ref_Department(models.Model):
	DepartmentID = models.AutoField(primary_key=True)
	DepartmentName = models.CharField(max_length=50)

	def natural_key(self):
		return self.DepartmentName

class Group(models.Model):
	GroupID = models.AutoField(primary_key=True)
	GroupName = models.CharField(max_length=50, default='')
	lab = models.ForeignKey('Ref_Laboratory', on_delete=models.CASCADE,default=0)
	Adviser = models.IntegerField(default=0)
	GroupStatus = models.IntegerField(default=0)
	Members = models.IntegerField(default=0)

	def natural_key(self):
		return self.GroupName

class User(models.Model):
	UserID = models.IntegerField(primary_key=True)
	NFCUniqueID = models.CharField(max_length=250, blank=True, null=True)
	UserType = models.IntegerField(default=0)
	Type = models.ForeignKey('Ref_UserType',on_delete=models.CASCADE,default=0,blank=True, null=True)
	UserStatus = models.IntegerField(default=0)
	Name = models.CharField(max_length=50, default='')
	IDNumber = models.IntegerField(default=0)
	PhoneNumber = models.IntegerField(default=0)
	Email = models.CharField(max_length=50, default='')
	Remarks = models.CharField(max_length=250, default='')
	group = models.ForeignKey('Group', on_delete=models.CASCADE,default=0,blank=True, null=True)
	adviser = models.ForeignKey('User', on_delete=models.CASCADE,default=0,blank=True, null=True)
	Degree = models.ForeignKey('Ref_Degree', on_delete=models.CASCADE,default=0,blank=True, null=True)
	Department = models.ForeignKey('Ref_Department', on_delete=models.CASCADE,default=0,blank=True, null=True)
	Laboratory = models.ForeignKey('Ref_Laboratory',  on_delete=models.CASCADE,default=0,blank=True, null=True)
	def get_id(self):
	    return self.UserID

	def get_UserType(self):
		return self.UserType

	def natural_key(self):
		return self.Name, self.UserID, self.IDNumber

class ActualResidency(models.Model):
	ActualResidencyID = models.AutoField(primary_key=True)
	Student = models.ForeignKey('User',  on_delete=models.CASCADE,default=0,blank=True, null=True)
	DateTime = models.DateField()
	TimeIn = models.TimeField()
	TimeOut = models.TimeField(blank=True, null=True)
	ResidencyType = models.IntegerField(blank=True, null=True)
	ResidencyStatus = models.IntegerField(blank=True, null=True)
	Schedule =  models.CharField(max_length=50,default='')

class Ref_Term(models.Model):
	TermID = models.AutoField(primary_key=True)
	Term = models.CharField(max_length=50, default='')
	StartDate = models.DateTimeField(blank=True, null=True)
	StartDate = models.DateTimeField(blank=True, null=True)

class Ref_Laboratory(models.Model):
	LabID = models.AutoField(primary_key=True)
	LaboratoryName = models.CharField(max_length=50, default='')
	RoomNum = models.CharField(max_length=50, default='')
	Capacity = models.IntegerField(default=0)
	Status = models.IntegerField(default=0)

	def get_LaboratoryName(self):
		return self.LaboratoryName

	def get_id(self):
	    return self.LabID

	def natural_key(self):
		return self.LaboratoryName, self.LabID

class Ref_Schedule(models.Model):
	ScheduleID = models.AutoField(primary_key=True)
	Day = models.CharField(max_length=20, default='')
	Time = models.TimeField()

	def natural_key(self):
		return self.Time

		class Meta:
        		ordering = ['Time']

class ResidencyTimeSlot(models.Model):
	ResidencyID = models.AutoField(primary_key=True)
	Laboratory = models.ForeignKey('Ref_Laboratory',  on_delete=models.CASCADE,default=0,blank=True, null=True)
	Schedule = models.CharField(max_length=50, default='')
	TotalSlot = models.IntegerField(default=0)
	TakenSlot = models.IntegerField(default=0)
	SchedVar = models.IntegerField(default=0)

class StudentResidencySchedule(models.Model):
	StudentResSchedID = models.AutoField(primary_key=True)
	RefSchedVar = models.IntegerField(default=0)
	StudentSchedVar = models.IntegerField(default=0)
	Student =  models.CharField(max_length=250,default='')
	Schedule =  models.CharField(max_length=50,default='')
	DateReserved = models.DateField(default=datetime.date.today)
	DateChanged = models.DateField(default=None, blank=True, null=True)

class Ref_AuditAction(models.Model):
	AuditActionID = models.AutoField(primary_key=True)
	Action = models.CharField(max_length=50, default='')

class Inventory(models.Model):
	ItemID = models.AutoField(primary_key=True)
	ItemName = models.CharField(max_length=50, default='')
	Description = models.CharField(max_length=50, default='')
	ItemType = models.CharField(max_length=50, default='')
	Quantity = models.IntegerField(default=0)
	ItemUniqueID = models.CharField(max_length=250, blank=True, null=True)
	QtyBorrowed = models.IntegerField(default=0)
	ItemStatus = models.IntegerField(default=1) 

	def natural_key(self):
		return self.ItemName, self.Description, self.ItemType

class AuditTable_Inventory(models.Model):
	AuditID = models.AutoField(primary_key=True)
	AuditAction = models.IntegerField(default=0)
	ItemID = models.ForeignKey('Inventory',on_delete=models.CASCADE,default=0,blank=True, null=True)
	Quantity = models.IntegerField(blank=True,null=True)
	DateTime = models.DateTimeField()
	DateTimeReturned = models.DateTimeField(blank=True,null=True)
	Borrower = models.ForeignKey('User',on_delete=models.CASCADE,related_name="borrower_users",blank=True, null=True)
	Admin = models.ForeignKey('User',on_delete=models.CASCADE,related_name="admin_users",blank=True, null=True)
	BorrowStatus = models.IntegerField(blank=True, null=True)
	Event = models.IntegerField(blank=True,default=0)
	Remarks = models.CharField(max_length=250,default='')

ARC/forms.py
from django import forms
from .models import Inventory, User

class InventoryForm(forms.Form):
	
	class Meta:
		itemname = forms.CharField()
		description = forms.CharField()
		item_type = forms.CharField()
		quantity = forms.IntegerField()
		uid = forms.IntegerField()
		
class LaboratoryForm(forms.Form):
	
	class Meta:
		labname = forms.CharField()
		roomno = forms.CharField()
		capacity = forms.IntegerField()
		
class TermForm(forms.Form):
	
	class Meta:
		termname = forms.CharField()
		startdate = forms.DateField()
		enddate = forms.DateField()
	
class FacultyRegistrationForm(forms.Form):

	class Meta:
		uniqueid = forms.IntegerField()
		idnum = forms.IntegerField()
		email = forms.CharField()
		first_name = forms.CharField()
		last_name = forms.CharField()
		mobileno = forms.IntegerField()

class StudentRegistrationForm(forms.Form):

	class Meta:
		uniqueid = forms.IntegerField()
		idnum = forms.IntegerField()
		email = forms.CharField()
		first_name = forms.CharField()
		last_name = forms.CharField()
		mobileno = forms.IntegerField()
		adviser = forms.IntegerField()

class AddGroupForm(forms.Form):

	class Meta:
		groupname = forms.CharField()
		laboratory = forms.IntegerField()
		adviser = forms.IntegerField()

class AddAccount(forms.Form):
	class Meta:
		accounttype = forms.IntegerField()
		email = forms.CharField()

ARC/templates/Faculty/FacultyManageGroups.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ARC | </title>

  	{% include 'import-css.html' %}

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
         <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title">
              <p class="site_title"><img src="{% static 'production/images/sidebar-logo.png' %}" id="sidebar-logo"> ARC</a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->

            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            {% include 'faculty-sidebar.html' %}
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>

                <ul class="nav navbar-nav navbar-right">
                  <li class="">
                    <a href="{%url 'logout' %}">Log Out &nbsp;<i class="fa fa-sign-out-alt"></i></a>
                  </li>
                </ul>

                  <ul class="nav navbar-nav navbar-left">
                    <li id="welcome-banner">
                      Welcome! {{faculty.Name}}
                    </li>
                  </ul>

            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Manage Groups</h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

								<!-- START Table-->
                <div class="row">
        					<div class="col-md-12 col-sm-12 col-xs-12">

        						<div class="clearfix">

                    <form method="POST" action="">{% csrf_token %}

          						<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                        <thead style="background-color: #4CAF50; color:white;">
                          <tr>
                            <th style="width: 23%">Group Name</th>
                            <th style="width: 8%">Group Members</th>
                            <th>Laboratory</th>
                            <th>Status</th>
                            <th style="width: 15%">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for Group in group_set %}
                          <tr>
                            <td>{{Group.GroupName}}</td>
                            <td>{{Group.Members}}</td>
                            <td>{{Group.lab.LaboratoryName}}</td>
                            {% if Group.GroupStatus == 1 %}
                            <td>Active</td>
                            {% else %}
                            <td>Inactive</td>
                            {% endif %}
                            <td class="actions"><button type="button" id="{{Group.GroupID}}" class="btn btn-primary" onclick="editClick(this)" data-toggle="modal" data-target=".div-edit-group-modal" value="">&nbsp;Edit Group&nbsp;</button></td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>

                    </form>

                    </div>
        					</div>

						      <!-- END Table-->

                  <!-- MODAL FOR USER DETAILS -->
                  <!-- MODAL FOR USER DETAILS -->

                  <div class="modal fade div-edit-group-modal" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-dialog modal-sm" id="edit-group-modal">
                  <div class="modal-content">

                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                      </button>
                      <h4 class="modal-title" id="myModalLabel2">Group Information</h4>
                    </div>
                    <div class="modal-body">

                    <form method="POST" action="" class="form-horizontal form-label-left">{% csrf_token %}



                          <div style="margin-left: 10px" class="form-group">
                            <label class="control-label col-md-2 col-xs-12" for="quantity">Group Name</label>
                            <div class="col-md-8 col-sm-6 col-xs-12" id="group-name">

                              <!-- AJAX -->

                            </div>
                          </div>

                          <div style="margin-left: 10px" class="form-group">
                            <label class="control-label col-md-2 col-xs-12">Laboratory</label>
                            <div class="col-md-8 col-sm-6 col-xs-12">
                              <select id="lab" class="form-control" name="lab" required>
                              </select>
                            </div>
                          </div>

                        <br>
                        <div style="margin-left:20px;" id="edit_member">

                          <div class="form-group">
                            <div class="col-md-7" style="width:620px;">
                            <select multiple="multiple" id="non-member" size="8" name="members[]" required>

                              <!-- AJAX -->

                            </select>
                            </div>
                          </div>

                        </div>

                    <div class="modal-footer" id="footer-buttons">
                      <!-- AJAX -->
                    </div>

                    </form>

                  </div>
                  </div>
                  </div>

                  <!-- END MODAL FOR USER DETAILS -->
                  <!-- END MODAL FOR USER DETAILS -->

                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

    {% include 'import-js.html' %}

    <script>

      var membereditor = $('select[name="members[]"]').bootstrapDualListbox({
        selectedListLabel: 'Current Members',
        nonSelectedListLabel: 'Available Students'
      });

      function editClick(elem) {
        var id = elem.id;

        $.ajax({

          url: "ajax/managegroups",
          method: "POST",
          data:{ 'id': id, 'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val() },

          success: function(data){

            $('#group-name').empty();
            $('#lab').empty();
            $('#not-member').empty();
            $('#footer-buttons').empty();
            $('#non-member').empty();

            var newdata = JSON.parse(data);
            console.log(newdata);

            var lab = [];
            var member = [];
            var nonmember = [];

            var x = 0;
            var y = 0;
            var z = 0;

            for (var i = 1; i < newdata.length; i++) {

              if (newdata[i].model == 'ARC.user' && newdata[i].fields.group == null) {

                nonmember[x] = newdata[i].pk; // store user id
                nonmember[x+1] = newdata[i].fields.Name;  // store user name

                //console.log(nonmember[x+1]);

                x+=2;

              }

              else if (newdata[i].model == 'ARC.user' && newdata[i].fields.group != null) {

                member[y] = newdata[i].pk;
                member[y+1] = newdata[i].fields.Name;
                y+=2;

              }

              else if (newdata[i].model == 'ARC.ref_laboratory') {

                lab[z] = newdata[i].pk;
                lab[z+1] = newdata[i].fields.LaboratoryName;
                z+=2;

              }
            }

            $('#footer-buttons').append(

              '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>\
              <button type="submit" class="btn btn-success" name="submit" value="'+ newdata[0].pk +'">Accept Changes</button>'

            );

            for (var i = 0; i < member.length; i+=2) {

              $('#footer-buttons').append(

                '<input type="hidden" name="orig_member_id[]" value="'+ member[i] +'">'

              );

            }

            $('#group-name').append(
              '<input type="input" name="groupname" value="'+ newdata[0].fields.GroupName +'" required="required" class="form-control col-md-12 col-xs-12">'
            );

            $('#lab').append(
              '<option value="'+ newdata[0].fields.lab[1] +'">'+ newdata[0].fields.lab[0] +'</option>'
            );

            // All for loops are incremented by 2 because the arrays are
            // filled with the order of: lab[0] = id, lab[0+1] = description
            // That means lab[0] = 0, lab[0+1] = cehci, lab[2] = 1, lab[2+1] = cite4d, etc...

            for (var i = 0; i < lab.length; i+=2) { // Populate labs dropdown
              if (lab[i+1] != newdata[0].fields.lab[0]) {

                $('#lab').append(
                  '<option value="'+ lab[i] +'">'+ lab[i+1] +'</option>'
                );

              }
            }


            for (var i = 0; i < nonmember.length; i+=2) { // Populate non member box

                $('#non-member').append(
                  '<option value="'+ nonmember[i] +'">'+ nonmember[i+1] +'</option>'
                );

            }

            // ############## START DUAL LIST BOX POPULATE ############## //

            for (var i = 0; i < member.length; i+=2) { // Populate non member box

                $('#non-member').append(
                  '<option value="'+ member[i] +'" selected="selected">'+ member[i+1] +'</option>'
                );

            }

            membereditor.bootstrapDualListbox('refresh');

            // ############## END DUAL LIST BOX POPULATE ############## //

          }

        });

      }

    </script>

    {% block check %}
      {% for c in Check %}
        {% if c == 'Success' %}

          <script>

            new PNotify({
              title: 'Done Editing a Group',
              text: 'You have successfully edited a group!',
              type: 'success',
              styling: 'bootstrap3'
            });

          </script>

        {% endif %}
      {% endfor %}
    {% endblock %}

  </body>
</html>